---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:
  rules:
    - name: Process Gitea push event
      condition: event.meta.headers.X_Gitea_Event == "push"
      action:
        run_playbook:
          name: test.yml
          extra_vars:
            gitref: "{{ event.payload.ref }}"
            repo_name: "{{ event.payload.repository.name }}"
            author: "{{ event.payload.head_commit.author.username }}"
            clone_url: "{{ event.payload.repository.clone_url }}"
            test_message: "{{ event.payload.head_commit.message }}"
          post_events: true

          #    - name: Log all incoming events
          # condition: true
          # action:
          # debug:
          # msg: "Received event: {{ event }}"

