---
- name: Process Gitea Push Event
  hosts: all
  gather_facts: false
  vars:
    full_message: "{{ test_message }}"
    split_message: "{{ full_message.split('\n') }}"
    extracted_message: "{{ split_message[2] }}"
  tasks:
  
    - name: Replace "Kunal" with "{{ xyz }}" in index.html
      ansible.builtin.replace:
        path: "/home/kpusdeka/index.html"
        regexp: 'value="*"'
        replace: 'value="{{ extracted_message }}"'
        
    - name: Print the rendered webpage using Chromium
      command: >
        chromium-browser --headless --disable-gpu --print-to-pdf=/tmp/webpage.pdf ~/index.html 

    - name: Send the PDF to the printer
      command: lp -d APAC_SecurePrint_IPP webpage.pdf
